services:
  - type: web
    name: dom-seniora-frontend
    env: node
    plan: free
    buildCommand: npm install --force && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://dom-seniora-backend.onrender.com
